language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t pbuczma/docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pbuczma/docker-test npm run test

after_success:
  - docker build -t pbuczma/multi-client:v1 ./client
  - docker build -t pbuczma/multi-nginx ./nginx
  - docker build -t pbuczma/multi-server ./server
  - docker build -t pbuczma/multi-worker ./worker
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pbuczma/multi-client
  - docker push pbuczma/multi-nginx
  - docker push pbuczma/multi-server
  - docker push pbuczma/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
