language: generic

sudo: required
services:
  - docker

before_install:
  - docker build -t pbuczma/docker-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pbuczma/docker-test npm run test

after_success:
  - docker build -t pbuczma/multi-client ./client
  - docker build -t pbuczma/multi-nginx ./nginx
  - docker build -t pbuczma/multi-server ./server
  - docker builr -t pbuczma/multi-worker ./worker
  - echo "DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push pbuczma/multi-client
  - docker push pbuczma/multi-nginx
  - docker push pbuczma/multi-server
  - docker push pbuczma/multi-worker
